### PR TITLE
Make some command parameters optional

### LINKED ISSUE #39: Allowing for incomplete commands
Currently the absence of required parameters in a command causes an error. For example, `\foo{\textbf}` parses as

```
(document [0, 0] - [1, 0]
  (cs [0, 0] - [0, 4])
  (ERROR [0, 4] - [1, 0]
    (l [0, 4] - [0, 5])
    (cs [0, 5] - [0, 12])
    (verb_delim [0, 12] - [0, 13])))
```

If the enclosing command is known to have control sequences as parameters this can be accounted for. For instance, `\def\textbf{\foo}` parses as

```
(document [0, 0] - [1, 0]
  (storage [0, 0] - [0, 17]
    (cs [0, 0] - [0, 4])
    (cs [0, 4] - [0, 11])
    (group [0, 11] - [0, 17]
      (l [0, 11] - [0, 12])
      (cs [0, 12] - [0, 16])
      (r [0, 16] - [0, 17])))
  (text [0, 17] - [1, 0]))
```

Since it is probably impossible to anticipate all commands that have control sequences as parameters this will have to be accounted for in the grammar.

### PR DESCRIPTION
**Pull request by yitzchak**
Resolves #39

### CODE REVIEW

**Comment by Aerijo** [comment]
@yitzchak I thought `tree-sitter-cli` is only a dev dependency?

**Comment by yitzchak** [comment]
@Aerijo It probably is, but the change in the install command appears to have made it impossible to install in language-latex via a github reference.

**Comment by Aerijo** [comment]
We need to change that entirely though, to use `prebuild` or similar. Regular users are unlikely to have build tools installed.

**Comment by yitzchak** [comment]
@Aerijo I agree. Even moving the tree-sitter-cli to `dependencies` temporarily doesn't work on my system. `tree-sitter genereate` appears to want to use the local node vs Atom's node.

```
Error: The module '/home/yitzi/Documents/git/language-latex/node_modules/tree-sitter-cli/build/Release/tree_sitter_cli_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 67. Please try re-compiling or re-installing
```

**Pull request merged**
