### PR TITLE
Catcode scanner

### PR DESCRIPTION
**Pull request by yitzchak**
Add a catcode based scanner

- [ ] Support expl syntax
- [ ] Add tests
- [ ] Remove all references to category contents from `grammar.js`

### CODE REVIEW

**Comment by yitzchak** [comment]
@Aerijo Take a look at this one please. There is still some kludges and some cleanup work to do (still one reference to the content of categories in `grammar.js`) but it is ready for an overall review.

**Comment by Aerijo** [comment]
I admit, I panicked when I first saw you went off the rails. But now I see you're not looking up every single character in the file for it's catcode, just ones in a command.

Some general comments:
- Instead of a map for catcodes, what about a switch statement into an array (or just an array, and use character as index)? I feel that we can also treat letters as constant catcode, and switches should be faster than map lookups.
  - Supporting catcode user changes (beyond ExplSyntaxOn) is probably impossible to do right, especially with commands like `\dospecials`. I'd sooner have the user disable syntax highlighting (or use a simplified version).

- We need to serialise the map

- If you want to stick with special casing `@`, we'd need a way to know if the file has `@` as a word character by default. 

- Is the vector and map stuff in a struct legal? I don't know C++ (I'm just going off my limited C knowledge), but Tree-sitter (the C++ parser) is having trouble with it, specifically inside of the struct. I'd raise an issue, but I'm not sure if it is a bug or not. It only seems to have trouble with the first one though. It's weird.

Otherwise looks reasonable. I'm sure we'll find (and fix) bugs as we go though.

**Comment by yitzchak** [comment]
- I agree that a switch or an array would be faster, but I am concerned about size. RIght now the advantage of a map is that if the character is not in the map then I just assume it is category "other". The majority of characters would be in this category in a utf8 file.
  - I do think that it is possible to support other more complex catcode switching mechanisms, but we should probably try that in a different PR to avoid snowballing complexity.

- I agree that the map needs to be serialized. My gut feeling to attempt this in a separate PR. thoughts?

- I don't know how to determine if `@` is a letter in a file that doesn't have an explicit catcode change. Are you thinking a in subfile via `\include`?

- The only difference between structs and classes is member default access level. In a struct everything is assumed to be public. Most people don't use structs with member functions since this is bad data encapsulation. We should probably switch to a class, IMHO.

**Comment by Aerijo** [comment]
- A map lets us add arbitrary characters. A switch statement can handle a fixed set of characters. We can try the map for now, but I'd like to see how the performance changes the other way too.

- For detecting catcode switching of arbitrary characters, how complicated are you imagining it? Even when only supporting direct changes, we'd still have to track group scope. For it to be somewhat accurate, it also needs to recognise commands that can reach the code change (and their scope). And of course, supporting it in the arbitrary case is equivalent to compiling the file; conditionals make it all impossible.

- Sure, we can do a separate PR. I like the general direction, so I'll merge this one now and we can then add improvements and make changes as needed.

- For `@`, we currently use the same grammar for all LaTeX files, including `.sty`, `.cls`, etc. In a subfile is also a possibility. I think it's safer (and less complex) to treat `@` as always a letter, and have no special behaviour for it. The potential downside here is `\foo@bar` would look like a single command, but 
  1. this could be picked up by a linter (which the user can configure). 
  2. 99% of the time it's supposed to be one command. If a user legitimately wants it separate, they can type `\foo @bar` for the exact same result. 
   1. The only issue might be inline verbatim, which could be special cased. E.g., `\verb@foo@` has very different behaviour depending on if `@` is a letter or not. It's so obscure I'm not that concerned though.

- Class is fine, I just copied the outline from the HTML grammar

**Comment by Aerijo** [comment]
@yitzchak FYI, I raised an issue about the weird struct behaviour, and it was patched almost immediately. So that's nice.

**Comment by yitzchak** [comment]
@Aerijo Great!

**Pull request merged**
